# Generated by Django 3.0.5 on 2021-10-30 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50, verbose_name='marca')),
                ('line', models.CharField(max_length=50, verbose_name='linea')),
                ('color', models.CharField(default='null', max_length=50, verbose_name='color')),
                ('detail', models.CharField(default='null', max_length=50, verbose_name='detalles')),
                ('price', models.DecimalField(decimal_places=2, max_digits=50, verbose_name='precio')),
                ('visible', models.BooleanField(default='null')),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
