# Generated by Django 3.0.5 on 2021-11-01 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20211030_1836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='price',
        ),
    ]
