# Generated by Django 3.0.5 on 2021-11-01 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_remove_vehicle_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='price',
            field=models.DecimalField(decimal_places=2, default='null', max_digits=50, verbose_name='precio'),
        ),
    ]
