# Generated by Django 3.0.5 on 2021-10-30 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.TextField(max_length=50, verbose_name='marca')),
                ('line', models.TextField(max_length=50, verbose_name='linea')),
                ('price', models.TextField(max_length=50, verbose_name='precio')),
            ],
        ),
    ]
